name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7', '3.6']
    steps:
      - name: Install openslide
        run: |
          sudo apt-get update
          sudo apt-get install --yes openslide-tools
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tyler
        run: python -m pip install --no-cache-dir --editable .[dev]
      - name: Check types
        run: mypy -m tyler
      - name: Check style
        run: flake8 tyler.py
      - name: Run python tests
        run: pytest
      - name: Upload code coverage
        run: codecov
